name: Docker CI

on:
  push:
    branches: [ LabWork5 ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Run Tests
        run: docker compose up --build --exit-code-from integration-tests
      - name: Check Logs
        if: always()
        run: docker compose logs integration-tests